// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/empiricaly/recruitment/internal/ent/admin"
	"github.com/empiricaly/recruitment/internal/ent/procedure"
	"github.com/empiricaly/recruitment/internal/ent/project"
	"github.com/empiricaly/recruitment/internal/ent/run"
	"github.com/empiricaly/recruitment/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescCreatedAt is the schema descriptor for createdAt field.
	adminDescCreatedAt := adminFields[1].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the createdAt field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUpdatedAt is the schema descriptor for updatedAt field.
	adminDescUpdatedAt := adminFields[2].Descriptor()
	// admin.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	admin.DefaultUpdatedAt = adminDescUpdatedAt.Default.(func() time.Time)
	// admin.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	admin.UpdateDefaultUpdatedAt = adminDescUpdatedAt.UpdateDefault.(func() time.Time)
	procedureFields := schema.Procedure{}.Fields()
	_ = procedureFields
	// procedureDescCreatedAt is the schema descriptor for createdAt field.
	procedureDescCreatedAt := procedureFields[1].Descriptor()
	// procedure.DefaultCreatedAt holds the default value on creation for the createdAt field.
	procedure.DefaultCreatedAt = procedureDescCreatedAt.Default.(func() time.Time)
	// procedureDescUpdatedAt is the schema descriptor for updatedAt field.
	procedureDescUpdatedAt := procedureFields[2].Descriptor()
	// procedure.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	procedure.DefaultUpdatedAt = procedureDescUpdatedAt.Default.(func() time.Time)
	// procedure.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	procedure.UpdateDefaultUpdatedAt = procedureDescUpdatedAt.UpdateDefault.(func() time.Time)
	// procedureDescName is the schema descriptor for name field.
	procedureDescName := procedureFields[3].Descriptor()
	// procedure.NameValidator is a validator for the "name" field. It is called by the builders before save.
	procedure.NameValidator = func() func(string) error {
		validators := procedureDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// procedureDescParticipantCount is the schema descriptor for participantCount field.
	procedureDescParticipantCount := procedureFields[5].Descriptor()
	// procedure.DefaultParticipantCount holds the default value on creation for the participantCount field.
	procedure.DefaultParticipantCount = procedureDescParticipantCount.Default.(int)
	// procedure.ParticipantCountValidator is a validator for the "participantCount" field. It is called by the builders before save.
	procedure.ParticipantCountValidator = procedureDescParticipantCount.Validators[0].(func(int) error)
	// procedureDescAdult is the schema descriptor for adult field.
	procedureDescAdult := procedureFields[8].Descriptor()
	// procedure.DefaultAdult holds the default value on creation for the adult field.
	procedure.DefaultAdult = procedureDescAdult.Default.(bool)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for createdAt field.
	projectDescCreatedAt := projectFields[1].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the createdAt field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updatedAt field.
	projectDescUpdatedAt := projectFields[2].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	runFields := schema.Run{}.Fields()
	_ = runFields
	// runDescCreatedAt is the schema descriptor for createdAt field.
	runDescCreatedAt := runFields[1].Descriptor()
	// run.DefaultCreatedAt holds the default value on creation for the createdAt field.
	run.DefaultCreatedAt = runDescCreatedAt.Default.(func() time.Time)
	// runDescUpdatedAt is the schema descriptor for updatedAt field.
	runDescUpdatedAt := runFields[2].Descriptor()
	// run.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	run.DefaultUpdatedAt = runDescUpdatedAt.Default.(func() time.Time)
	// run.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	run.UpdateDefaultUpdatedAt = runDescUpdatedAt.UpdateDefault.(func() time.Time)
}
