// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Procedure is the predicate function for procedure builders.
type Procedure func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Run is the predicate function for run builders.
type Run func(*sql.Selector)

// StepRun is the predicate function for steprun builders.
type StepRun func(*sql.Selector)
