// Code generated by entc, DO NOT EDIT.

package steprun

const (
	// Label holds the string label denoting the steprun type in the database.
	Label = "step_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStartAt holds the string denoting the startat field in the database.
	FieldStartAt = "start_at"
	// FieldEndedAt holds the string denoting the endedat field in the database.
	FieldEndedAt = "ended_at"
	// FieldParticipantsCount holds the string denoting the participantscount field in the database.
	FieldParticipantsCount = "participants_count"

	// Table holds the table name of the steprun in the database.
	Table = "step_runs"
)

// Columns holds all SQL columns for steprun fields.
var Columns = []string{
	FieldID,
	FieldStartAt,
	FieldEndedAt,
	FieldParticipantsCount,
}
